### ISSUE TITLE
Package locales does not exist on CentOS 6.5

### ISSUE THREAD

**Issue by mjhodgkinson** [attachmentgenie/attachmentgenie-locales#9]
/Stage[main]/Locales/Package[locales]/ensure 	
change from absent to present failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install locales' returned 1: Error: Nothing to do

Unsure what the correct package would be on CentOS.

**Comment by SPQRInc** [comment]
Got the same problem here.

**Comment by attachmentgenie** [comment]
the metadata.json file erroneously stated that the rhel family was a supported family. However this module only ever supported the debian os family. I corrected this mistake for the 2.0.0 release.
